// lib/cashscript.mjs — manual signing primitive for covenant inputs (P2SH containing CashScript)
//
// Why this exists:
// libauth's compiler path (walletTemplateP2pkhNonHd + walletTemplateToCompilerBCH) works
// for plain P2PKH and even for token-bearing P2PKH spends with sighash 0x41 (Selene's
// proven production pattern). But for covenant inputs (P2SH containing a CashScript
// function contract), the compiler can't help — we need to build the unlocking bytecode
// by hand: <push sig_with_sighash_byte> <push pubkey> <push redeemscript>.
//
// The signing serialization is generated by libauth's `generateSigningSerializationBCH` which
// requires `outputTokenPrefix` from the source UTXO. For covenant inputs, the source UTXO
// is itself a token-bearing P2SH, so we MUST pass the token data through.
//
// Pattern: Selene's KeyManagerService.signTemplate (gitlab.com/selene.cash/selene-wallet).
//
// Sighash flag is ALWAYS 0x61 for covenant inputs (CHIP-2022-02-CashTokens requires it
// for any input spending a CashTokens-bearing source output).

import {
  secp256k1,
  sha256,
  hash256,
  generateSigningSerializationBCH,
  cashAddressToLockingBytecode,
  SigningSerializationFlag,
} from '@bitauth/libauth';

import { binToHex, hexToBin } from './hex.mjs';

/**
 * Build the unlocking bytecode for a covenant input:
 *   <push sig_with_sighash_byte> <push pubkey> <push redeemscript>
 *
 * Returns a Uint8Array ready to be placed in input.unlockingBytecode.
 *
 * @param {object} args
 * @param {Uint8Array} args.signature - 64-byte Schnorr signature
 * @param {Uint8Array} args.publicKey - 33-byte compressed pubkey
 * @param {Uint8Array} args.redeemScript - the function contract bytecode (P2SH witness)
 * @param {number} args.sighashType - 0x61 = SIGHASH_ALL | SIGHASH_UTXOS | SIGHASH_FORKID
 * @returns {Uint8Array}
 */
export function buildCovenantUnlockingBytecode({ signature, publicKey, redeemScript, sighashType }) {
  // Append sighash type byte to the signature (per BCH consensus rules).
  // The signature pushed onto the stack includes the sighash byte at the end.
  const sigWithSighash = new Uint8Array(signature.length + 1);
  sigWithSighash.set(signature, 0);
  sigWithSighash[signature.length] = sighashType;

  // Push opcode for sig: <push length_byte> <sig_with_sighash>
  // Length can be up to 0x4b (75). For Schnorr 64-byte sig + 1 sighash = 65 bytes,
  // we use OP_PUSHBYTES_65 = 0x41. Falls within standard push range (< 0x4c).
  const unlocking = new Uint8Array(
    1 + sigWithSighash.length +
    1 + publicKey.length +
    1 + redeemScript.length
  );
  let offset = 0;
  // push sig with sighash
  unlocking[offset++] = sigWithSighash.length;  // OP_PUSHBYTES_N for N in 1-75
  unlocking.set(sigWithSighash, offset); offset += sigWithSighash.length;
  // push pubkey
  unlocking[offset++] = publicKey.length;
  unlocking.set(publicKey, offset); offset += publicKey.length;
  // push redeemscript (the function contract bytecode)
  unlocking[offset++] = redeemScript.length;
  unlocking.set(redeemScript, offset);

  return unlocking;
}

/**
 * Compute the sighash for a covenant input.
 *
 * Mirrors `libauth.generateSigningSerializationBCH` + the SHA256d step:
 *   1. Serialize the tx's signing-relevant fields per SIGHASH_ALL | SIGHASH_UTXOS | SIGHASH_FORKID
 *   2. SHA256 the serialization
 *   3. SHA256 the hash → 32-byte digest to sign
 *
 * Caller must pass the FULL source output (with real lockingBytecode + token), not a stub.
 * This is the workaround for libauth's TODO at generate-transaction.js:42 — we do manually
 * what the compiler can't.
 *
 * @param {object} args
 * @param {number} args.inputIndex - index of this input in the tx
 * @param {Uint8Array} args.outpointTransactionHash - LE-encoded txid of the spent UTXO
 * @param {number} args.outpointIndex - output index in the parent tx
 * @param {Uint8Array} args.coveredBytecode - the redeemscript that the sig commits to
 * @param {Uint8Array} args.outputTokenPrefix - libauth's encodeTokenPrefix(token) of source
 * @param {bigint} args.outputValue - sat value of source output
 * @param {Array<{tx_hash, tx_pos}>} args.allOutpoints - for hashPrevouts
 * @param {Array<Uint8Array>} args.allOutputTokenPrefixes - one per input, for hashUtxos
 * @param {Array<{valueSatoshis: bigint, lockingBytecode: Uint8Array, token?: object}>} args.allSourceOutputs - one per input (with real bytecode!)
 * @param {Array<bigint>} args.allSequenceNumbers
 * @param {Array<{valueSatoshis: bigint, lockingBytecode: Uint8Array, token?: object}>} args.transactionOutputs
 * @param {number} args.version
 * @param {number} args.locktime
 * @returns {Uint8Array} 32-byte sighash digest
 */
export async function computeCovenantSighash(args) {
  const sighashType = new Uint8Array([SigningSerializationFlag.allOutputs
    | SigningSerializationFlag.utxos
    | SigningSerializationFlag.forkId]);

  const compilationContext = {
    inputIndex: args.inputIndex,
    sourceOutputs: args.allSourceOutputs,    // REAL bytecode + token
    transaction: {
      version: args.version,
      locktime: args.locktime,
      inputs: args.allOutpoints.map((o, i) => ({
        outpointIndex: i,
        outpointTransactionHash: hexToBin(o.tx_hash).slice().reverse(),
        sequenceNumber: args.allSequenceNumbers[i] ?? 0n,
        unlockingBytecode: new Uint8Array(), // placeholder; compiler doesn't use
      })),
      outputs: args.transactionOutputs,
    },
  };

  const coveredBytecode = args.coveredBytecode;
  const outputTokenPrefix = args.outputTokenPrefix;

  // generateSigningSerializationBCH expects (sourceOutput, outpoint, etc.) — let it compute.
  const serialization = generateSigningSerializationBCH(compilationContext, {
    coveredBytecode,
    signingSerializationType: sighashType,
  });
  // SHA256d (double SHA256) → 32-byte digest
  return hash256(serialization);
}

/**
 * Sign a covenant input's sighash and return the Schnorr signature.
 *
 * @param {Uint8Array} sighash - 32-byte digest from computeCovenantSighash
 * @param {Uint8Array} privateKey - 32-byte private key for the address
 * @returns {Uint8Array} 64-byte Schnorr signature
 */
export async function signCovenantSighash(sighash, privateKey) {
  const sig = secp256k1.signMessageHashSchnorr(privateKey, sighash);
  if (typeof sig === 'string') throw new Error(`Schnorr sign failed: ${sig}`);
  return sig;
}

/**
 * High-level helper: sign a covenant input and produce the complete unlocking bytecode.
 *
 * @param {object} args - all params needed for computeCovenantSighash + signCovenantSighash + buildCovenantUnlockingBytecode
 * @param {Uint8Array} args.privateKey
 * @param {Uint8Array} args.publicKey - 33-byte compressed pubkey matching privateKey
 * @returns {Uint8Array} complete unlocking bytecode ready to drop into input.unlockingBytecode
 */
export async function signCovenantInput(args) {
  const sighashType = 0x61;
  const sighash = await computeCovenantSighash(args);
  const signature = await signCovenantSighash(sighash, args.privateKey);
  return buildCovenantUnlockingBytecode({
    signature,
    publicKey: args.publicKey,
    redeemScript: args.coveredBytecode,
    sighashType,
  });
}

export { SigningSerializationFlag };